### ISSUE TITLE
Unity Rigidbody axis transferred to parent GameObject

### ISSUE THREAD

**Issue by NiklasRosenstein** [project-unik/racing#1]
This is either me being stupid and not understand why it works the way it does, or it's a bug in the Unity Editor. And its extremely confusing.
1. Create an empty GameObject
2. Create a Cube as a child of it
3. Add a Rigidbody component to the Cube
4. Play and see the Cube falling to the floor (eventually add a floor object beforehand)
5. Also note how the parent GameObject's axis moves **with the cube** in the Editor, but its actual values in the _Transform_ component stay the same

Quick video to demonstrate the problem: https://vid.me/8BNj

Unity 5.3.3f1

**Comment by ElhamMGS** [comment]
This is no bug. Unity generally places the axis at the center of mass. Given that the empty object and camera have no mass, the center is in the cube. When moving, the center of mass stays inside the cube thus the axis is moving with the cube.
