### ISSUE TITLE
Objects in Unity update functions

### ISSUE THREAD

**Issue by lukasstevens** [project-unik/racing#2]
When looking at the update functions I often see patterns like this:
`Vector3 torque = Vector3.Cross(predictedUp, upVector);`
If the code does not get optimized (one question is; will get optimized?) then this object is created and destroyed every update. In theory this should create a noticable performance impact when the number of objects excedes a certain threshold.
So my questions is: has anybody had experience with this issue and is it necessary to optimize the code?

**Comment by rafiwui** [comment]
i think we should optimize as much as we can. i don't have experiance with this special case but i think you're right with the performance impact. so the question is when do we really need this sort of code and just execute it when it is to be used.

Are you using this code and where? And what is it doing in your script?

**Comment by kappelmann** [comment]
Short answer: No, it's not necessary to optimize that code.

"Premature optimization is the root of all evil" - Donald Knuth
