### ISSUE TITLE
Set ForceMode when applying a force with addForce

### ISSUE THREAD

**Issue by lukasstevens** [project-unik/racing#6]
When applying a force like this;
`rigidBody.addForce(force)`
one should use the appropiate ForceMode:
`rigidBody.addForce(force, ForceMode.Acceleration)`

This is to account for the mass of the rigid body accordingly. For further information check the Unity documentation: [http://docs.unity3d.com/ScriptReference/ForceMode.html](http://docs.unity3d.com/ScriptReference/ForceMode.html)
I have already set the ForceMode accordingly in my branch. Perhaps everybody should pull my version to avoid merge conflicts later on.

**Comment by lukasstevens** [comment]
Or pull dev/lukas into master.

**Comment by kappelmann** [comment]
Merged into master branch.
