### ISSUE TITLE
For text files: provide one format which is viewable on GitHub

### ISSUE THREAD

**Issue by lukasstevens** [project-unik/racing#7]
@Dudadei 
When pushing text files to GitHub it would be benficial to provide one format which is viewable on GitHub (pdf, txt, md) for easier viewing on the web.
Even better would be a cross-platform format, for example LaTeX. Optionally the compiled pdf can be provided with the LaTeX source.

**Comment by lukasstevens** [comment]
@Fr3ak1n0ut 
Would be nice if the whole design team would at least provide a pdf version of every docx file.

**Comment by fewhnhouse** [comment]
@lukas-123 
Ill let the design team members know that in the future, we will upload pdf files instead of docx.
@Dudadei 
Please update the corresponding file.
